# SPDX-FileCopyrightText: Nextcloud GmbH
# SPDX-FileCopyrightText: 2025 Iva Horn
# SPDX-License-Identifier: GPL-3.0-or-later

name: Documentation

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
      - name: Build documentation
        run: |
          xcodebuild docbuild \
            -scheme NextcloudFileProviderKit \
            -destination 'platform=macOS' \
            -skipPackagePluginValidation \
            -derivedDataPath ./DerivedData
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting ./DerivedData/Build/Products/Debug/NextcloudFileProviderKit.doccarchive \
            --output-path ./docs \
            --hosting-base-path /nextcloudfileproviderkit
      - name: Create root redirect
        run: |
          cat > ./docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>NextcloudFileProviderKit Documentation</title>
            <meta http-equiv="refresh" content="0; url=./documentation/nextcloudfileproviderkit/">
            <link rel="canonical" href="./documentation/nextcloudfileproviderkit/">
          </head>
          <body>
            <p>Redirecting to <a href="./documentation/nextcloudfileproviderkit/">NextcloudFileProviderKit Documentation</a>...</p>
            <script>
              window.location.href = "./documentation/nextcloudfileproviderkit/";
            </script>
          </body>
          </html>
          EOF
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
  Deploy: # See: https://github.com/actions/deploy-pages
    needs: Build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4